# lambda-template/.github/workflows/deploy.yml
name: Deploy Lambda

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: acs-lambda/.github/workflows/deploy-lambda.yml@main
    with:
      function-name: DBCreate
      region: us-east-2
    secrets:
      GHA_AWS_ROLE_ARN: ${{ secrets.GHA_AWS_ROLE_ARN }}
