# lambda-template/.github/workflows/deploy.yml
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: acs-lambda/.github/.github/workflows/deploy-lambda.yml@main
    with:
      function-name: aws-lambda-function-name-here   # ← Change this to the AWS Lambda Function Name!
      region: us-east-2                 # optional
